name: Daily Test

on:
  schedule:
    - cron: '13 13 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'ubuntu-20.04'
          - 'ubuntu-18.04'
          - 'ubuntu-16.04'
          - 'macos-latest'
          - 'windows-latest'
        version:
          - 'latest'
          - '0.2.19'
    steps:
      - uses: actions/checkout@v2

      - name: Setup act
        uses: actionsflow/setup-act@v1
        with:
          version: ${{ matrix.version }}

      - name: Run act version
        run: echo "::set-output name=act_version::$(act version)"
        id: act_version

      - name: '${{ steps.act_version.outputs.act_version }}'
        run: echo '${{ steps.act_version.outputs.act_version }}'
